# Generated by Django 5.1.3 on 2024-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_venuerequest_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuerequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
