# Generated by Django 5.1.3 on 2024-11-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_venuerequest_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuerequest',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
