# Generated by Django 5.1.3 on 2024-11-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_remove_venuerequest_file_upload_venuerequest_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VenueRequest',
        ),
    ]
