# Generated by Django 5.1.3 on 2024-11-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity_delete_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
