# Generated by Django 5.1.3 on 2024-11-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventVenue',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
